Added owner to the list
meateam/web-ui pull request #103
Opened 2019-12-01 10:58 UTC by Shahar-Y

tested and works
Signed-off-by: shahar-y <shya95@gmail.com>

2019-12-01 11:23 UTC, omrishtam requested changes
Deploy it to your environment before merging.

2019-12-05 14:25 UTC, Shahar-Y commented
Available in http://jntn.northeurope.cloudapp.azure.com/

2019-12-05 14:43 UTC, omrishtam approved these changes

2020-08-12 10:21 UTC, Shahar-Y commented
Closing due to irrelevance to the public

2020-08-12 10:21 UTC, closed without merging