WIP: Feature/external share
meateam/web-ui pull request #119
Opened 2020-01-29 00:21 UTC by Shahar-Y

Added the external share component. Tested with docker-compose.

Need to approve with kubernetes after adding delegation-service to kd-helm.

2020-03-18 07:37 UTC, yonatandt requested changes

2020-03-18 07:37 UTC, AllKinds commented on docker-compose.yml
> +    image: 'bluehub.azurecr.io/meateam/api-gateway:merges'
change it back to develop

2020-03-18 07:37 UTC, AllKinds commented on docker-compose.yml
> +      ELASTICSEARCH_URL: http://13.69.137.179:9200
don't show IP

2020-03-18 07:37 UTC, AllKinds commented on docker-compose.yml
> +      ELASTIC_APM_SERVER_URL: 'http://13.69.137.179:8200'
don't show IP

2020-03-18 07:37 UTC, AllKinds commented on public/index.html
> +  img.omri-spinner {
```suggestion
  img.loading-logo {
```

2020-03-18 07:37 UTC, AllKinds commented on public/index.html
> +    <img src="/img/yesodot_logo.svg" alt="" class="omri-spinner">
```suggestion
    <img src="/img/yesodot_logo.svg" alt="" class="loading-logo">
```

2020-03-18 07:37 UTC, AllKinds commented on src/api/users.js
> +}
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/store/getters.js
> +  isVIP: state => state.isVIP,
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/store/index.js
> +  isVIP: undefined,
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/store/mutations.js
> +  },
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/utils/constants.js
> +	vipServiceUrl: 'localhost:8094',
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/utils/constants.js
> +	config.vipServiceUrl = conf.vipServiceUrl;
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/utils/constants.js
> +	config.externalExclusiveUnit = conf.externalExclusiveUnit;
Not relevant anymore

2020-03-18 07:37 UTC, AllKinds commented on src/utils/constants.js
> +	externalExclusiveUnit: 'יחידת ביג מאם',
Not relevant anymore

2020-04-02 07:42 UTC, yonatandt requested changes

2020-04-02 07:42 UTC, AllKinds commented on docker-compose.yml
> +      ELASTIC_APM_SERVER_URL: 'http://13.69.137.179:8200'
Still here...

2020-04-05 12:43 UTC, Shahar-Y commented
Closing for #135

2020-04-05 12:43 UTC, closed without merging