added user service and redis to docker-compose.yml .Tested and works.
meateam/web-ui pull request #90
Opened 2019-10-24 06:59 UTC by Shahar-Y

Signed-off-by: shahar-y <shya95@gmail.com>

2019-10-30 11:43 UTC, AllKinds commented on docker-compose.yml
> +    image: 'file-service:local'
Change it to `bluehub.azurecr.io/meateam/` as well

2019-11-04 09:12 UTC, omerzamir requested changes

2019-11-04 09:12 UTC, omerzamir commented on docker-compose.yml
> +      - user-service
should also depend on permission-service

2019-11-04 16:05 UTC, omerzamir approved these changes

2019-11-04 16:05 UTC, merged